In [4]:
from Selection import Bentley
from Selection import FrequencyDependent
import pandas
from scipy.stats import logistic
from joblib import Parallel, delayed
import multiprocessing
import random
import numpy as np
import pandas

In [57]:
np.random.choice(10, size=100, p=np.repeat(0.1, 10))

array([2, 9, 9, 7, 0, 0, 5, 5, 0, 2, 3, 5, 0, 6, 1, 3, 5, 8, 6, 8, 4, 8, 0,
       9, 3, 1, 0, 1, 2, 8, 1, 9, 9, 4, 7, 5, 9, 3, 2, 1, 0, 3, 9, 6, 4, 1,
       7, 7, 7, 7, 7, 6, 8, 0, 6, 6, 1, 0, 1, 9, 7, 8, 8, 2, 5, 3, 9, 0, 3,
       8, 7, 4, 0, 5, 8, 2, 5, 2, 6, 5, 4, 2, 4, 6, 7, 3, 4, 0, 3, 8, 3, 6,
       0, 8, 3, 7, 9, 3, 0, 1])

In [23]:
np.random.randint(0, 10, size=10)

array([1, 0, 9, 7, 0, 0, 7, 8, 0, 8])

In [26]:
persons = np.random.randint(0, 10, size=10)
lNumber = []
for people in persons:
    lNumber.append(people)

In [31]:
lTemp = pandas.Series(lNumber)
lTemp = lTemp.to_frame()
lTemp['number'] = lTemp.index
lTemp['number'].isin([3])

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: number, dtype: bool

In [36]:
import collections
cnt = collections.Counter()
for number in lNumber:
    cnt[number] += 1

In [49]:
float(cnt[2]) / 33

0.030303030303030304

In [50]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [51]:
np.ones(5) / 10

array([ 0.1,  0.1,  0.1,  0.1,  0.1])